module.exports = {
  FETCH_POKEMON: 'FETCH_POKEMON',
  FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
  FETCH_POKEMON_FAILED: 'FETCH_POKEMON_FAILED',

  FETCH_SINGLE_POKEMON: 'FETCH_SINGLE_POKEMON',
  FETCH_SINGLE_POKEMON_SUCCESS: 'FETCH_SINGLE_POKEMON_SUCCESS',
  FETCH_SINGLE_POKEMON_FAILED: 'FETCH_SINGLE_POKEMON_FAILED',

  REMOVE_DETAIL_POKEMON: 'REMOVE_DETAIL_POKEMON',
};
